version: '3'
services:
  php:
    image: php-debug:latest
    ports:
      - 8080:80
    volumes:
      - './mnt:/var/www'
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: dev
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql